apiVersion: v2
name: idempotentapi
description: Home work num.6 Otus

type: application

version: 0.1.0
appVersion: v1

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled