#Пользователи
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordersservice-deployment
  labels:
    app: ordersservice
spec:
  replicas: {{ .Values.ordersservice.replicaCount }}   
  selector:
    matchLabels:
      app: ordersservice
  template:
    metadata:
      labels:
        app: ordersservice
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: userservice
          image: "{{ .Values.ordersservice.image.repository }}:{{ .Values.ordersservice.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /hc
              port: 8000
          readinessProbe:
            httpGet:
              path: /hc
              port: 8000
          env:
          - name: ORDERS_URI
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: ORDERS_URI
          - name: JWT_Key
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_Key
          - name: JWT_Issuer
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_Issuer
          - name: JWT_Audience
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_Audience
          volumeMounts:
          - name: configmap-volume
            mountPath: "/app/appsettings.json"
            subPath: appsettings.json
            readOnly: true
      volumes:
      - name: configmap-volume
        configMap:
          name: api-configmap