{{- if .Values.ingress.enabled -}}
{{- $fullName := include "idempotentapi.fullname" . -}}
{{- $ordersSvcPort := .Values.ordersservice.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: ordersservice-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
        - path: /orders(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: ordersservice-service
              port:
                number: {{$ordersSvcPort}} 
{{- end }}